### ISSUE TITLE
Get covers from Open Library (Internet Archive)

### ISSUE THREAD

**Issue by stweil** [UB-Mannheim/vMaBookShelf#3]
The Open Library offers a simple [API to get cover images](https://openlibrary.org/dev/docs/api/covers). This API contains some cover images which are not available at Amazon, so it might be useful to get all (or only missing) cover images from Open Library.

Examples:
- http://covers.openlibrary.org/b/isbn/3406328148-L.jpg
- http://covers.openlibrary.org/b/isbn/3476008355-L.jpg

**Comment by BFallert** [comment]
was realized with 0.9.14, additionally covers are taken by Google and Syndetics.
